// Generated by jextract

package dev.atsushieno.panama.libremidi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libremidi_api_configuration {
 *     enum libremidi_api api;
 *     enum {
 *         Observer,
 *         Input,
 *         Output
 *     } configuration_type;
 *     void *data;
 * }
 * }
 */
public class libremidi_api_configuration {

    libremidi_api_configuration() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libremidi_c_h.C_INT.withName("api"),
        libremidi_c_h.C_INT.withName("configuration_type"),
        libremidi_c_h.C_POINTER.withName("data")
    ).withName("libremidi_api_configuration");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt api$LAYOUT = (OfInt)$LAYOUT.select(groupElement("api"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum libremidi_api api
     * }
     */
    public static final OfInt api$layout() {
        return api$LAYOUT;
    }

    private static final long api$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum libremidi_api api
     * }
     */
    public static final long api$offset() {
        return api$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum libremidi_api api
     * }
     */
    public static int api(MemorySegment struct) {
        return struct.get(api$LAYOUT, api$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum libremidi_api api
     * }
     */
    public static void api(MemorySegment struct, int fieldValue) {
        struct.set(api$LAYOUT, api$OFFSET, fieldValue);
    }

    private static final OfInt configuration_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("configuration_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * enum {
     *     Observer,
     *     Input,
     *     Output
     * } configuration_type
     * }
     */
    public static final OfInt configuration_type$layout() {
        return configuration_type$LAYOUT;
    }

    private static final long configuration_type$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * enum {
     *     Observer,
     *     Input,
     *     Output
     * } configuration_type
     * }
     */
    public static final long configuration_type$offset() {
        return configuration_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum {
     *     Observer,
     *     Input,
     *     Output
     * } configuration_type
     * }
     */
    public static int configuration_type(MemorySegment struct) {
        return struct.get(configuration_type$LAYOUT, configuration_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum {
     *     Observer,
     *     Input,
     *     Output
     * } configuration_type
     * }
     */
    public static void configuration_type(MemorySegment struct, int fieldValue) {
        struct.set(configuration_type$LAYOUT, configuration_type$OFFSET, fieldValue);
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

