
plugins {
    id ("application")
    alias(libs.plugins.kotlin.jvm)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}
application {
    mainClass = "DriverKt"
}

dependencies {
    implementation(project(":libremidi-panama"))
    implementation(libs.jne)
    implementation(libs.kotlin.stdlib)
}
repositories {
    mavenCentral()
}

